@api_local = http://localhost:3000

### Health Check
GET {{api_local}}/health

### Login
POST {{api_local}}/auth/login
Content-Type: application/json

{
   "email": "testes@testes.com",
   "password": "senha123" 
}

### Register
POST {{api_local}}/auth/register
Content-Type: application/json

{
   "name": "Anderson",
   "email": "testes@testes.com",
   "password": "senha123",
   "confirmPassword": "senha123"
}

### Confirm Email (com token válido)
GET {{api_local}}/auth/confirm-email?token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJlODBhZGM0ZC01NDQ0LTQ2ZDItYWIxMS1mNWU4NWNjNDQ4ZGEiLCJlbWFpbCI6ImFuZGVyc29uQGFuZGVyc29uLmNvbSIsImlhdCI6MTc2NzMwMTczMywiZXhwIjoxNzY3MzAyNjMzfQ.Egf4qPuJvw3n1k4r_ADtnFHdEr2FN6VbmbR_HEQoJlQ

### Confirm Email (sem token - deve dar erro 400)
GET {{api_local}}/auth/confirm-email

### Confirm Email (com token inválido - deve dar erro 401)
GET {{api_local}}/auth/confirm-email?token=token_invalido_aqui