@api_local = http://localhost:3000
###Register
# @name Register
POST {{api_local}}/auth/register
Accept: application/json
User-Agent: RestClient

{
   "name": "credential" ,
   "email": "credential@credential.com",
   "password": "credential"
}

### Confirm Email (com token válido)
GET {{api_local}}/auth/confirm-email?token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJkYjI2YmJmYy1iOGMwLTQ0ZDgtYjI0YS03OGNmMmU4Zjc3Y2YiLCJlbWFpbCI6ImNyZWRlbnRpYWxAY3JlZGVudGlhbC5jb20iLCJpYXQiOjE3NjcwMzUzMDQsImV4cCI6MTc2NzAzNjIwNH0.QlFErJsS6VniCDUPWrNGfbnq15cr74p6YDBZRSHKPLY

### Login
POST {{api_local}}/auth/login

{
   "email": "credential@credential.com",
   "password": "credential"
}


### Request Credential Reset
# @name RequestCredentialReset
POST {{api_local}}/api/credential
Content-Type: application/json

{
   "email": "credential@credential.com"
}


### Credential Reset
# @name CredentialReset
PUT {{api_local}}/api/credential
Content-Type: application/json

{
   "token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJkYjI2YmJmYy1iOGMwLTQ0ZDgtYjI0YS03OGNmMmU4Zjc3Y2YiLCJlbWFpbCI6ImNyZWRlbnRpYWxAY3JlZGVudGlhbC5jb20iLCJpYXQiOjE3NjcwMzUzOTEsImV4cCI6MTc2NzAzNTY5MX0.HmUxquI9KjBGDV2GWwAuACtgMSm3KIZKFmO0oMhjKpw",
   "password": "credential1"
}

### Login
POST {{api_local}}/auth/login

{
   "email": "credential@credential.com",
   "password": "credential1"
}


